### ISSUE TITLE
叶先生（或者是奥总）的“致谢”

### ISSUE THREAD

**Issue by GardenChen** [FiimeOS/Notice#1]
在您最新的“Notcie.md”里提到了本人，这是我的荣幸，我没想到事情过去半年了您依旧死不悔改，反正您觉得不在酷安就没问题，其他平台就可以随便蹦跶了是吧？本来一开始盗用我的截图我也没想做什么，只是您的态度让我感觉不像在道歉，而是阴阳怪气捏,于是继续深查才发现了您的伟大计划：画饼耍猴，还不忘人血馒头，看了一遍，原谅我笑出了声，通篇都是可怜巴巴，球球别丢人了，Notice写成Notcie我真的会笑，别洗地啦好不好，不行咱进厂打工吧，赚钱不寒碜🤣🤣

**Comment by aoaoemoji** [comment]
对不起，我不用你的吃你的，也和你没有任何交集，我愿意干什么，在哪里蹦跶，怎么写notice都与你无关，你还是待在你的酷安吧，我并不觉得丢人，只是讲的事实，半年过去了，我洗哪门子白？我不碍着你啥，你也别恶心人。用你的图在这里给你道歉了，关于fiimeos的事情，是不是大饼已经不重要了，多谢你的关心。
